# Main configuration for the pipeline
# Based on structure set up by `set_up_folders.py`, change paths to customize for different project structure.

[paths]
# Default project-level paths
meta_dir = "0_Metadata"
data_dir = "1_Recordings"
dataset_dir = "2_Datasets"
# Paths to data and output within recording folders.
raw_dir = "0_raw_compressed"
processed_dir = "2_processed"
alignment_dir = "1_histology_alignment"
output_dir = "3_datasets"

# [logging] # Not currently used
# project_prefix = ""
# log_level = "INFO"
