# Project/Run configuration for the pipeline
# Update parameters for project and subject/recordings

[experiment]
dir = ""

[experiment.recordings]
# if multiple recordings to concatenate, set concatenate = true
# for multiple shank probes:
#    set multiple_shanks = true or list of booleans for each probe
#    if multiple probes, set multiple_shanks = list of booleans
# Example:
ANIMALID_R1 = { concatenate = false, multiple_shanks = true }
